import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

// A single awarded-points entry from the student's ledger (GET /points).
export interface TranscriptRow {
  title: string;
  clubName?: string | null;
  type?: string;
  points: number;
  date: string;
}

export interface TranscriptStudent {
  name?: string;
  usn?: string;
  college?: string;
  year?: number;
  semester?: number;
  lateralEntry?: boolean;
  requiredPoints?: number;
}

const esc = (v: unknown) =>
  String(v ?? '').replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c] as string));

function buildHtml(student: TranscriptStudent, rows: TranscriptRow[]): string {
  const total = rows.reduce((s, r) => s + (r.points || 0), 0);
  const required = student.lateralEntry ? 80 : student.requiredPoints ?? 100;
  const pct = Math.min(100, Math.round((total / required) * 100));
  const generatedOn = new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' });

  const sorted = [...rows].sort((a, b) => (a.date < b.date ? 1 : -1));
  const rowsHtml = sorted.length
    ? sorted
        .map(
          (r, i) => `
        <tr style="background:${i % 2 ? '#F8FAFC' : '#FFFFFF'}">
          <td>${esc(r.date)}</td>
          <td>${esc(r.title)}</td>
          <td>${esc(r.clubName || '—')}</td>
          <td>${esc(r.type || 'Activity')}</td>
          <td style="text-align:right;font-weight:600;color:#4F46E5">+${r.points}</td>
        </tr>`
        )
        .join('')
    : `<tr><td colspan="5" style="text-align:center;color:#94A3B8;padding:24px">No points awarded yet.</td></tr>`;

  return `<!DOCTYPE html><html><head><meta charset="utf-8"/>
  <style>
    * { font-family: -apple-system, Helvetica, Arial, sans-serif; box-sizing: border-box; }
    body { margin: 0; padding: 40px; color: #0F172A; }
    .brand { display:flex; align-items:center; gap:10px; margin-bottom:4px; }
    .logo { width:34px; height:34px; border-radius:9px; background:linear-gradient(135deg,#06B6D4,#4F46E5); color:#fff; font-weight:700; font-size:20px; display:flex; align-items:center; justify-content:center; }
    h1 { font-size:22px; margin:0; }
    .sub { color:#64748B; font-size:12px; margin-top:2px; }
    .card { border:1px solid #E2E8F0; border-radius:12px; padding:18px 20px; margin-top:22px; }
    .grid { display:flex; flex-wrap:wrap; gap:18px 40px; }
    .field .l { color:#64748B; font-size:11px; text-transform:uppercase; letter-spacing:.04em; }
    .field .v { font-size:15px; font-weight:600; margin-top:2px; }
    .summary { display:flex; align-items:center; justify-content:space-between; margin-top:22px; padding:18px 20px; border-radius:12px; background:#0F172A; color:#fff; }
    .summary .big { font-size:30px; font-weight:700; }
    .summary .lbl { font-size:12px; color:#94A3B8; }
    .bar { height:8px; border-radius:99px; background:#1E293B; margin-top:8px; overflow:hidden; width:220px; }
    .bar > div { height:100%; background:linear-gradient(90deg,#06B6D4,#4F46E5); }
    table { width:100%; border-collapse:collapse; margin-top:14px; font-size:13px; }
    th { text-align:left; color:#64748B; font-size:11px; text-transform:uppercase; letter-spacing:.04em; border-bottom:2px solid #E2E8F0; padding:8px 10px; }
    td { padding:9px 10px; border-bottom:1px solid #F1F5F9; }
    .foot { margin-top:30px; color:#94A3B8; font-size:11px; text-align:center; }
  </style></head>
  <body>
    <div class="brand"><div class="logo">P</div><div><h1>PointsTrack</h1><div class="sub">AICTE Activity Points — Transcript</div></div></div>

    <div class="card"><div class="grid">
      <div class="field"><div class="l">Name</div><div class="v">${esc(student.name)}</div></div>
      <div class="field"><div class="l">USN</div><div class="v">${esc(student.usn)}</div></div>
      <div class="field"><div class="l">College</div><div class="v">${esc(student.college)}</div></div>
      <div class="field"><div class="l">Year / Sem</div><div class="v">${esc(student.year ?? '—')} / ${esc(student.semester ?? '—')}</div></div>
      <div class="field"><div class="l">Entry</div><div class="v">${student.lateralEntry ? 'Lateral' : 'Regular'}</div></div>
    </div></div>

    <div class="summary">
      <div><div class="lbl">Total points earned</div><div class="big">${total} <span style="font-size:16px;color:#94A3B8">/ ${required}</span></div>
        <div class="bar"><div style="width:${pct}%"></div></div>
      </div>
      <div style="text-align:right"><div class="lbl">Completion</div><div class="big">${pct}%</div></div>
    </div>

    <table>
      <thead><tr><th>Date</th><th>Activity</th><th>Organizer</th><th>Category</th><th style="text-align:right">Points</th></tr></thead>
      <tbody>${rowsHtml}</tbody>
    </table>

    <div class="foot">Generated by PointsTrack on ${esc(generatedOn)} · This is a system-generated transcript.</div>
  </body></html>`;
}

// Builds the transcript PDF from the student's ledger and opens the OS share
// sheet so they can save / send it. Throws if sharing is unavailable.
export async function generateTranscript(student: TranscriptStudent, rows: TranscriptRow[]) {
  const { uri } = await Print.printToFileAsync({ html: buildHtml(student, rows) });
  if (!(await Sharing.isAvailableAsync())) {
    throw new Error('Sharing is not available on this device.');
  }
  await Sharing.shareAsync(uri, {
    mimeType: 'application/pdf',
    dialogTitle: 'AICTE Points Transcript',
    UTI: 'com.adobe.pdf',
  });
}
