'use client'

import Link from 'next/link'
import Navbar from '@/components/landing/navbar'
import Footer from '@/components/landing/footer'
import { motion } from 'framer-motion'
import { ArrowLeft, QrCode, Database, Lock, Eye } from 'lucide-react'

const securityFeatures = [
  {
    icon: QrCode,
    title: 'Cryptographic Check-Ins',
    description:
      'Every event pass generated by our system is cryptographically signed. Organizers scanning these passes immediately query a live database to ensure the token hasn\'t been duplicated or exhausted by bad actors.',
    accent: 'from-cyan-500 to-blue-600',
    tag: 'Anti-Fraud',
  },
  {
    icon: Database,
    title: 'Immutable Point Ledger',
    description:
      'Once points are successfully disbursed by an organizer, they are written to an immutable student ledger. These records are read-only for students, completely preventing unauthorized point inflation.',
    accent: 'from-violet-500 to-blue-600',
    tag: 'Data Integrity',
  },
  {
    icon: Eye,
    title: 'Data Privacy',
    description:
      'We do not sell student tracking data. Email hashes, pass generation, and organizational ties are strictly firewalled between authenticated collegiate realms.',
    accent: 'from-emerald-500 to-teal-600',
    tag: 'Privacy',
  },
  {
    icon: Lock,
    title: 'Role-Based Access Control',
    description:
      'Strict separation between College Admins, Event Organizers, and Students ensures each actor can only access and mutate data within their authorized scope.',
    accent: 'from-orange-500 to-red-600',
    tag: 'RBAC',
  },
]

const trustBadges = [
  { label: 'Cryptographic QR Passes' },
  { label: 'Immutable Point Ledger' },
  { label: 'Role-Based Access Control' },
  { label: 'No Data Selling' },
  { label: 'Encrypted Storage' },
  { label: 'Token-Based Auth' },
]

export default function SecurityPage() {
  return (
    <div className="min-h-screen bg-slate-950 flex flex-col">
      <Navbar />

      {/* Hero */}
      <section className="relative pt-36 pb-20 px-4 overflow-hidden">
        <div className="absolute inset-0 inner-page-gradient pointer-events-none" />
        <div className="absolute top-20 left-1/2 -translate-x-1/2 w-[600px] h-[200px] bg-blue-500/8 rounded-full blur-[80px] pointer-events-none" />
        <div className="dot-grid absolute inset-0 opacity-40 pointer-events-none" />

        <div className="relative max-w-4xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
          >
            <Link
              href="/"
              className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-cyan-400 mb-10 transition-colors group"
            >
              <ArrowLeft className="w-4 h-4 group-hover:-translate-x-0.5 transition-transform" />
              Back to Home
            </Link>

            <span className="section-label text-blue-400/80">Security & Trust</span>
            <h1 className="page-hero-title mb-6">
              Built with{' '}
              <span className="gradient-text-cyan">integrity</span>{' '}
              at its core
            </h1>
            <p className="text-xl text-slate-400 leading-relaxed max-w-2xl">
              PointsTrack takes the integrity of the AICTE point economy seriously. Our architecture
              uses enterprise-grade verification to eliminate fraudulent activities and ghost-attendances.
            </p>
          </motion.div>

          {/* Trust badges */}
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
            className="flex flex-wrap gap-2 mt-8"
          >
            {trustBadges.map((badge) => (
              <span
                key={badge.label}
                className="inline-flex items-center gap-1.5 text-xs font-medium px-3 py-1.5 rounded-full bg-slate-800/60 border border-slate-700/60 text-slate-300"
              >
                <span className="w-1.5 h-1.5 rounded-full bg-cyan-400 flex-shrink-0" />
                {badge.label}
              </span>
            ))}
          </motion.div>
        </div>
      </section>

      {/* Feature cards */}
      <section className="flex-1 px-4 pb-24">
        <div className="max-w-4xl mx-auto grid md:grid-cols-2 gap-5">
          {securityFeatures.map((feature, i) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 24 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.55, delay: 0.1 + i * 0.08 }}
              className="glass-card p-7 group"
            >
              <div className="flex items-start justify-between mb-5">
                <div
                  className={`w-11 h-11 rounded-xl bg-gradient-to-br ${feature.accent} flex items-center justify-center shadow-lg group-hover:shadow-xl transition-shadow flex-shrink-0`}
                >
                  <feature.icon className="w-5 h-5 text-white" />
                </div>
                <span className="text-xs font-semibold text-slate-400 bg-slate-800/60 border border-slate-700/50 px-2.5 py-1 rounded-full">
                  {feature.tag}
                </span>
              </div>
              <h2 className="text-lg font-bold text-white mb-3">{feature.title}</h2>
              <p className="text-slate-400 text-sm leading-relaxed">{feature.description}</p>
            </motion.div>
          ))}
        </div>
      </section>

      <Footer />
    </div>
  )
}
