import Link from 'next/link'
import Footer from '@/components/landing/footer'
import { ArrowLeft, ShieldCheck } from 'lucide-react'

export default function SecurityPage() {
  return (
    <div className="min-h-screen bg-slate-950 flex flex-col">
      <main className="flex-1 max-w-4xl mx-auto w-full px-4 py-20">
        <Link href="/" className="inline-flex items-center text-cyan-400 hover:text-cyan-300 mb-8 transition-colors">
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back to Home
        </Link>
        <div className="flex items-center gap-4 mb-8">
          <div className="p-3 bg-cyan-500/10 rounded-xl">
            <ShieldCheck className="w-8 h-8 text-cyan-400" />
          </div>
          <h1 className="text-4xl md:text-5xl font-bold text-white tracking-tight">Security & Trust</h1>
        </div>
        <div className="prose prose-invert prose-slate max-w-none">
          <p className="text-xl text-slate-300 leading-relaxed mb-12">
            PointsTrack takes the integrity of the AICTE point economy seriously. Our architecture uses enterprise-grade verification to eliminate fraudulent activities and ghost-attendances.
          </p>

          <h2 className="text-2xl font-bold text-white mb-4">Cryptographic Check-Ins</h2>
          <p className="text-slate-400 mb-8">
             Every event pass generated by our system is cryptographically signed. Organizers scanning these passes immediately query a live database to ensure the token hasn't been duplicated or exhausted by bad actors.
          </p>

          <h2 className="text-2xl font-bold text-white mb-4">Immutable Point Ledger</h2>
          <p className="text-slate-400 mb-8">
             Once points are successfully disbursed by an organizer, they are burned into an immutable student ledger in our Firebase Datastore. These documents are read-only for students, completely preventing unauthorized point inflation.
          </p>

           <h2 className="text-2xl font-bold text-white mb-4">Data Privacy</h2>
          <p className="text-slate-400">
             We do not sell student tracking data. Email hashes, pass generation, and organizational ties are strictly firewalled between authenticated collegiate realms.
          </p>
        </div>
      </main>
      <Footer />
    </div>
  )
}
